language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t luisfredo/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true luisfredo/docker-react npm run test